export const errorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",

  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",

  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_TYPE_MISMATCH: "CATEGORY_TYPE_MISMATCH",

  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",

  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",

  DUPLICATE_BUDGET: "DUPLICATE_BUDGET",
  INVALID_BUDGET_CATEGORY: "INVALID_BUDGET_CATEGORY",
} as const;